name: Update market data and deploy to GitHub Pages

on:
  schedule:
    - cron: '0,30 * * * *' # 每半小时更新一次（北京时间）
    - cron: '0,15,30,45 19-21 * * *' # 北京时间3-5点期间每15分钟更新一次（UTC 19-21点）
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Run update script
        env:
          BUFF_COOKIE_1: ${{ secrets.BUFF_COOKIE_1 }}
          BUFF_COOKIE_2: ${{ secrets.BUFF_COOKIE_2 }}
          BUFF_COOKIE_3: ${{ secrets.BUFF_COOKIE_3 }}
          BUFF_COOKIE_4: ${{ secrets.BUFF_COOKIE_4 }}
          BUFF_COOKIE: ${{ secrets.BUFF_COOKIE }}
          STEAM_COOKIE: ${{ secrets.STEAM_COOKIE }}
          DEBUG: ${{ vars.DEBUG || 'true' }}
        run: |
          echo "=== 开始执行数据更新 ==="
          echo "DEBUG 模式: $DEBUG"
          echo "当前时间: $(date)"
          
          # 确保等待命令完成
          timeout 1800 npm run update || {
            echo "=== 更新脚本超时或失败 ==="
            echo "退出码: $?"
            exit 1
          }
          
          echo "=== 数据更新完成 ==="
          echo "完成时间: $(date)"

      - name: Commit and push changes
        run: |
          echo "=== Git 状态检查 ==="
          git status
          echo "=== 检查文件变更 ==="
          git diff --name-only
          echo "=== 检查暂存区 ==="
          git diff --cached --name-only
          
          if ! git diff --quiet; then
            echo "=== 发现文件变更，准备提交 ==="
            git add data/data.json public/index.html
            git status
            git commit -m "chore: hourly data update and static page generation $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            echo "=== 推送到远程仓库 ==="
            git push origin HEAD:main
            echo "=== 推送完成 ==="
          else
            echo "No changes to commit"
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: update
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: # 如果有自定义域名，在这里填写


